
CREATE TABLE IF NOT EXISTS SENSORES (
    ID_SENSOR INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (100) NOT NULL,
    TIPO VARCHAR (100) NOT NULL    
);

CREATE TABLE IF NOT EXISTS ATUADORES (
    ID_ATUADOR INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (100) NOT NULL,
    TIPO VARCHAR (100) NOT NULL    
);

CREATE TABLE IF NOT EXISTS COMODO (
    ID_COMODO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (100) NOT NULL,
    LARGURA DOUBLE NOT NULL,
    COMPRIMENTO DOUBLE NOT NULL,
    ID_SENSOR INT NOT NULL,
    ID_ATUADOR INT NOT NULL
);

ALTER TABLE COMODO ADD CONSTRAINT IF NOT EXISTS FK_COMODO_SENSOR FOREIGN KEY(ID_SENSOR) REFERENCES SENSORES(ID_SENSOR) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE COMODO ADD CONSTRAINT IF NOT EXISTS FK_COMODO_ATUADOR FOREIGN KEY(ID_ATUADOR) REFERENCES ATUADORES(ID_ATUADOR) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS PROJETO (
    ID_PROJETO INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (100) NOT NULL,
    LOGIN VARCHAR (100) NOT NULL,
    SENHA VARCHAR (100) NOT NULL,
    ID_COMODO INT NOT NULL
);

ALTER TABLE PROJETO ADD CONSTRAINT IF NOT EXISTS FK_PROJETO_COMODO FOREIGN KEY(ID_COMODO) REFERENCES COMODO(ID_COMODO) ON DELETE CASCADE ON UPDATE CASCADE;